on: [push, pull_request]

name: irlba comparison

jobs:
  build:
    name: Compare to irlba reference
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    steps:
    - uses: actions/checkout@v1

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure the build 
      run: cmake -S . -B build -DBUILD_TESTING=OFF

    - name: Install packages
      shell: Rscript {0}
      run: |
        BiocManager::install(c("irlba", "Rcpp", "testthat"))

    - name: Build the test dependencies
      run: |
        cd tests/R
        bash build.sh

    - name: Run the comparisons
      shell: Rscript {0}
      run: |
        setwd("tests/R")
        output <- testthat::test_file("run.R")
        q(status=any(as.data.frame(output)$failed), save="no")
